packages:
  common: [git, zsh, gh, git-lfs, tmux, neovim, ripgrep, fzf, bat, chafa, git-delta, lsd, btop]
  fedora: [vim-enhanced, lazygit, fd-find, make, gcc, unzip, gettext, imv]
  debian: [vim, fd-find, make, gcc, unzip, gettext, imv]
  darwin: [lazygit, fd, ttyper]
